services:
  - type: web
    name: leaf-iq
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app.py --server.port=$PORT --server.address=0.0.0.0
    pythonVersion: 3.10.13
